CODE_OF_CONDUCT.md
GOVERNANCE.md

* `CODE_OF_CONDUCT`
* `GOVERNANCE`

Add standard TBD OSS files:

---

packages/http-client/package.json
packages/http-client/src/client.ts
packages/http-server/package.json
packages/http-server/src/fakes.ts
packages/http-server/src/types.ts
packages/protocol/json-schemas/offering.schema.json
packages/protocol/json-schemas/quote.schema.json
packages/protocol/json-schemas/rfq.schema.json
packages/protocol/package.json
packages/protocol/src/dev-tools.ts
packages/protocol/src/message-kinds/quote.ts
packages/protocol/src/message-kinds/rfq.ts
packages/protocol/src/resource-kinds/offering.ts
packages/protocol/src/types.ts
packages/protocol/tests/offering.spec.ts
packages/protocol/tests/rfq.spec.ts

* change `base*` and `quote*` fields to `payout*` and `payin*` respectively

Field name changes

---

package-lock.json
packages/http-client/package.json
packages/http-server/package.json
packages/http-server/src/request-handlers/submit-rfq.ts
packages/protocol/json-schemas/order.schema.json
packages/protocol/json-schemas/quote.schema.json
packages/protocol/package.json
packages/protocol/src/dev-tools.ts
packages/protocol/src/message-kinds/rfq.ts
packages/protocol/tests/rfq.spec.ts

* bump `@web5` packages
* add integrity check to `Rfq.verifyClaims`
* fix json schemas

Claims Integrity Check

---

packages/http-client/package.json
packages/http-server/package.json
packages/protocol/json-schemas/message.schema.json
packages/protocol/package.json

- Fix orderstatus
- Bump versions

Fix schema

---

README.md

Closes https://github.com/TBD54566975/tbdex-js/issues/32

Add guide for changesets usage

---

packages/http-client/src/client.ts
packages/http-client/src/types.ts
packages/http-server/src/http-server.ts
packages/http-server/src/types.ts

Fix and complete HTTP Client & Server docs

---

.github/workflows/npm-publish.yml

[This job](https://github.com/TBD54566975/tbdex-js/actions/runs/6620724272/job/17983632338) showed as passing but it actually failed 
- added check to actually fail in this case
- also installed semver to prevent error from occurring

Add semver installation to CI job

---

packages/http-client/CHANGELOG.md
packages/http-client/package.json
packages/http-client/src/client.ts
packages/http-server/CHANGELOG.md
packages/http-server/package.json
packages/http-server/src/types.ts
packages/protocol/CHANGELOG.md
packages/protocol/package.json

per current spec [here](https://github.com/TBD54566975/tbdex/tree/main/specs/http-api#list-exchanges)

changing get exchanges filter to have id instead of exchangeId

---

.changeset/dull-dots-repair.md
packages/protocol/src/types.ts

for: https://github.com/orgs/TBD54566975/projects/29/views/1?pane=issue&itemId=48146358

RequiredClaims is optional

---

.github/workflows/integrity-check.yml
.gitignore
CODEOWNERS
package.json
pnpm-lock.yaml

closes #119 
vuln to be fixed by: https://github.com/TBD54566975/tbdex-js/issues/132

setting up junit xml reporting

---

packages/protocol/src/dev-tools.ts
packages/protocol/src/message-kinds/quote.ts
packages/protocol/src/types.ts

Addresses https://github.com/TBD54566975/tbdex/issues/201
Update to `tbdex` spec: https://github.com/TBD54566975/tbdex/pull/223

Fold paymentInstructions inside payin and payout

---

.github/workflows/docs-publish.yml
packages/protocol/src/message-kinds/rfq.ts

Fix docs publish failures: https://github.com/TBD54566975/tbdex-js/actions/workflows/docs-publish.yml

Fix docs-publish.yaml

---

packages/protocol/src/crypto.ts
packages/protocol/src/dev-tools.ts
packages/protocol/src/did-resolver.ts
packages/protocol/src/message-kinds/rfq.ts
packages/protocol/src/message.ts
packages/protocol/src/resource-kinds/offering.ts
packages/protocol/src/resource.ts
packages/protocol/src/types.ts
packages/protocol/src/utils.ts
packages/protocol/tests/offering.spec.ts
packages/protocol/tests/rfq.spec.ts
packages/protocol/tests/tsconfig.json
packages/protocol/tsconfig.json

The other packages will be strictened in a follow up PR.

Stricten typescript in protocol package

---

.changeset/rotten-goats-marry.md
packages/http-client/src/client.ts
packages/http-client/tests/client.spec.ts
packages/http-server/src/http-server.ts
packages/http-server/src/request-handlers/create-exchange.ts
packages/http-server/src/request-handlers/get-exchange.ts
packages/http-server/src/request-handlers/submit-close.ts
packages/http-server/src/request-handlers/submit-message.ts
packages/http-server/src/request-handlers/submit-order.ts
packages/http-server/src/types.ts
packages/http-server/tests/create-exchange.spec.ts
packages/http-server/tests/get-exchange.spec.ts
packages/http-server/tests/submit-close.spec.ts
packages/http-server/tests/submit-message.spec.ts
packages/http-server/tests/submit-order.spec.ts

Addresses https://github.com/TBD54566975/tbdex-js/issues/196
New design here https://github.com/TBD54566975/tbdex/issues/225#issuecomment-1986057713

#196 Restructure http endpoints according to latest design

---

packages/protocol/tests/generate-test-vectors.ts

bump test vector for `Close`
https://github.com/TBD54566975/tbdex/pull/304

updating parse close vector with success field

---

packages/protocol/tests/test-vectors.spec.ts

TODO: after https://github.com/TBD54566975/tbdex/pull/303 merges, update the submodule commit

Refresh offerings test vector

---

packages/protocol/src/dev-tools.ts
packages/protocol/src/message-kinds/rfq.ts
packages/protocol/src/types.ts

Context: https://github.com/TBD54566975/tbdex-kt/pull/222#pullrequestreview-1971434556

DX Improvement: Unhashed* -> Create*

---

packages/protocol/src/message.ts
packages/protocol/src/resource.ts

At @mistermoe's request/suggestion.

Updated error message in verifySignature()

---

.github/workflows/integrity-check.yml
audit-ci.json
package-lock.json
package.json
packages/protocol/src/types.ts
pnpm-lock.yaml

Addresses compliance with spec as per: https://github.com/TBD54566975/tbdex-js/issues/249
cc @thehenrytsai

adding fee to fix issue #249

---

packages/http-server/README.md

Reported in https://discord.com/channels/937858703112155166/949067728709369856/1248621964436836514

Update broken link in http-server README

---

.changeset/mighty-carrots-jog.md
packages/protocol/src/dev-tools.ts
packages/protocol/src/types.ts

update quote payment instructions to comply with latest tbdex spec

update quote payment instructions

---

.github/workflows/integrity-check.yml

Add specs-report on CI

---

.github/workflows/integrity-check.yml

Follow up to a bug introduced in #273 (sorry 🙇 )

Fix tests step id
