TBD54566975/tbdex-js

.github/workflows/integrity-check.yml
.github/workflows/npm-publish.yml

Install [tbdocs-action](https://github.com/TBD54566975/tbdocs) which will have two main functionalities:
1. **Docs Reporter**: every PR against main will report the doc warnings and errors in the PR comment. The developer can feel free to correct them if they want to or ignore it for now. After releasing the v1 we should make this blocking.
2. **Publishing Docs to the developer.tbd.website**: on the Publish workflow now you have three options:
a. Publish npm: like it is today
b. Publish docs: will run the docs reporter (from step 1) and if it completes without errors it will generate the markdown files and open a PR to our website repo: https://github.com/TBD54566975/developer.tbd.website
c. Publish both: this will try to publish the docs by opening the PR, if it succeeds it will publish …

Setup TBDocs

---

.github/workflows/npm-publish.yml
packages/protocol/src/main.ts

It adds a brief summary and link to the repo on the index of the protocol docs.
As per request here: https://github.com/TBD54566975/tbdocs/issues/28
Using the `@packageDocumentation` was the key tag to add this summary in the docs!
Preview Link: https://deploy-preview-804--tbd-website-developer.netlify.app/docs/tbdex/api-reference/tbdex-js/protocol/
Summary preview:

Add @tbdex-js/protocol package doc

---

.github/workflows/integrity-check.yml
packages/protocol/src/crypto.ts

Introduces the flag `report_changed_scope_only: true`, which will filter the tbdocs reporter to show only the modified lines by the PR.
Working evidence:

Filter tbdocs-reporter to only changed files

---

.github/workflows/integrity-check.yml
.github/workflows/npm-publish.yml
packages/http-client/src/main.ts
packages/http-server/src/main.ts
packages/http-server/tsconfig.json

The PR https://github.com/TBD54566975/tbdocs/pull/39 enabled support to multiple packages.
Here we are adding the http-client and http-server to the docs reporter and generator.
Working evidences:
- The github action comment below with the report of the three packages. (no errors/warnings because no files were changed)
- The generated docs created here in our website: https://github.com/TBD54566975/developer.tbd.website/pull/873
Fix #43

Add http client and server docs

---

.changeset/seven-bears-stare.md
packages/http-client/src/client.ts
packages/http-server/tests/get-exchanges.spec.ts
packages/protocol/src/crypto.ts
packages/protocol/src/message.ts
packages/protocol/src/resource.ts
packages/protocol/tests/crypto.spec.ts
packages/protocol/tests/offering.spec.ts
packages/protocol/tests/rfq.spec.ts

> [!IMPORTANT]
> This PR changes the Public API surface for both `@tbdex/http-client` and `@tbdex/protocol`
This PR introduces a change to the arguments passed to functions that sign things, namely:
* `Message.sign` (e.g. `rfq.sign`, `quote.sign` etc.)
* `Resource.sign` (e.g. `offering.sign`)
```typescript
const did = await DidDhtMethod.create()
const rfq = Rfq.create({
metadata : { from: did.did, to: 'did:ex:pfi' },
data     : rfqData
})
const { privateKeyJwk } = did.keySet.verificationMethodKeys[0]
let verificationMethodId = `${did.did}#${did.document.verificationMethod[0].id}`
await rfq.sign(privateKeyJwk, verificationMethodId)
```
```typescript
const did = await DidDhtMethod.create()
const rfq = Rfq.create({
metadata : { from: did.did, to: 'did:ex:pfi' },
data     : rfqData
})
await …
```

Refactor sign

---

.github/workflows/create-gh-release.yml
.github/workflows/npm-publish.yml
README.md

This PR automates the trigger to create a GH Release when a changeset PR is merged.
Fix #60 (see full context context).
(Also it removes the TBDocs from the release pipeline because now we are planning to release default Typedoc similar to the  DWN ones).

Automate GitHub releases

---

.github/workflows/npm-publish.yml

the current release workflow is not triggering the npm publish... this PR fixes it.
Reason from [GH Docs](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow):
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.
And I was trying to trigger the `on: release`. Now I fixed the npm publish to be triggered when the new automated …

Fix npm publish trigger

---

.github/workflows/integrity-check.yml
.github/workflows/security.yml

- We are decoupling the security scanning to be able to run security checks on approved forks
- Plus, taking the opportunity to add FOSSA because we are assessing their security tooling and SBOMs generation

Decouples security scanning analysis and add FOSSA

---

.github/workflows/docs-ci.yml
.github/workflows/docs-publish.yml
packages/http-server/src/callback-error.ts

Preparing to publish to GH Pages on every new release automatically.
Preview link: https://tbd54566975.github.io/tbdex-js/index.html

Generates the HTML to publish to GH Pages

---

.vscode/settings.json
CODEOWNERS
package.json
pnpm-lock.yaml

Aligning on typescript version to be at `5.2.2` for VS Code `settings.json` and top level `package.json`
Part of an effort to break apart [this PR](https://github.com/TBD54566975/tbdex-js/pull/126) into smaller ones. Related to #122

adding default typescript version to align on

---

.changeset/real-schools-enjoy.md
packages/http-client/package.json
packages/protocol/package.json
packages/protocol/src/crypto.ts
packages/protocol/src/dev-tools.ts
packages/protocol/src/did-resolver.ts
packages/protocol/src/message-kinds/rfq.ts
packages/protocol/src/resource-kinds/offering.ts
packages/protocol/tests/crypto.spec.ts
packages/protocol/tests/rfq.spec.ts
pnpm-lock.yaml

Upgrading to latest versions of `@web5` packages (dids, common, crypto, credentials)
Removed dependency from `Jose` library in `Crypto.ts`
Using `DidResolver.dereference()` from `@web5/dids` package, which closes #147 
Using `VerifiableCredentials.create()` from `@web5/credentials` package instead of `DevTools.createCredential()`
Part of an effort to break apart https://github.com/TBD54566975/tbdex-js/pull/126 into smaller ones. Related to #122

bumping web5 versions

---

.changeset/mighty-pandas-speak.md
packages/http-client/src/client.ts
packages/http-client/src/errors/request-error.ts
packages/http-client/tests/client.spec.ts
packages/http-client/tests/tsconfig.json
packages/http-client/tsconfig.json

Turn on strict typescript and do a few small cleanups. Also, remove `discoverPFIs` because it seems to be untested, undocumented, absent from the spec, and riddled with typescript looseness that it doesn't seem worth strictening.

Stricten http-client

---

.changeset/green-cheetahs-share.md
packages/protocol/src/exchange.ts
packages/protocol/src/main.ts
packages/protocol/src/message-kinds/rfq.ts
packages/protocol/tests/exchange.spec.ts

This state machine class `Exchange` will be used to great effect in a follow-up PR in the http-server package.

Add exchange state machine

---

packages/protocol/tests/generate-test-vectors.ts

vectors now include `did:dht` DIDs for alice and pfi. PR for updated vectors here: https://github.com/TBD54566975/tbdex/pull/247
> [!WARNING]
> Do not merge until https://github.com/TBD54566975/tbdex/pull/247 is merged. Need to update this branch to use submodule `main` first

Test vector generation updates

---

packages/http-client/src/client.ts
packages/http-client/tests/client.spec.ts

Implements: https://github.com/TBD54566975/tbdex/issues/254 which is the same as https://github.com/TBD54566975/tbdex-js/issues/187

Split client sendMessage into separate methods

---

.github/workflows/integrity-check.yml
.github/workflows/release.yml
.gitignore

This PR is removing the recent hack introduced on #198 where we needed to add the unnecessary `setup-node` action which overlaps with hermit.
What they do under the hood, which was also my fix, is just to create the `.npmrc` with the registry url stating that we will use the NODE_AUTH_TOKEN.
Also I've added the `.hermit` folder to git ignore to prevent adding it by mistake in the Version Packages PR.
Working Evidence: #202

Set NPM Config Registry in .npmrc for the Release Workflow

---

.github/workflows/release-snapshot.yml

This is part of a project being undertaken by OSP to help new code make it's way to TBD's downstream projects faster. It creates a snapshot release for each merge to main, which is published to our Artifactory* registry. Once this is done, downstream projects (developer.tbd.website) can pull in new tbdex-js features before a real release has been produced by depending on the snapshot version.
*Artifactory: behaves like npmjs.com, but isn't real npmjs.com so the high number of releases this creates will not spam up our npmjs.com page.

build and publish snapshot releases on every merge to main

---

packages/http-server/package.json
packages/http-server/src/in-memory-offerings-api.ts
packages/http-server/tests/create-exchange.spec.ts
packages/http-server/tests/get-offerings.spec.ts
packages/protocol/build/compile-validators.js
packages/protocol/src/dev-tools.ts
packages/protocol/src/message-kinds/rfq.ts
packages/protocol/src/types.ts
packages/protocol/src/validator.ts
packages/protocol/tests/generate-test-vectors.ts
packages/protocol/tests/rfq.spec.ts
packages/protocol/tests/test-vectors.spec.ts
pnpm-lock.yaml

Implement spec changes from this PR: https://github.com/TBD54566975/tbdex/pull/269
There are currently no up-to-date test vectors for RFQ and Offerings. We can't create functioning test vectors until 2 tbdex SDKs have implemented these changes. I would prefer to take the following approach:
1. Merge these changes so this PR does not remain pending
2. Implement or have another engineer implement these changes in JS and KT
3. Regenerate and validate the test vectors in question
4. Open a new PR against tbdex-js to add the vectors.
| issue                                                  | tbdex commits …

Recent small spec changes

---

.changeset/lucky-waves-battle.md

Add changesets for recent changes:
- [Add balance resource and todos](https://github.com/TBD54566975/tbdex-js/commit/7edf7045a361915db9c4c2e2205989c5ce5209e1)
- [Create salted hashes of privateData in Rfq](https://github.com/TBD54566975/tbdex-js/commit/717dac3dbe615c18d5e218845d871a4bd221e39e)
- [Recent small spec changes](https://github.com/TBD54566975/tbdex-js/commit/02ce905201e58d4162ff75bb10f116bf7452b030)
- [Add Close.success](https://github.com/TBD54566975/tbdex-js/commit/fa959972743cc7f0b07b676b79b2aa51ca398df0)

add changeset

---

packages/http-client/.c8rc.json
packages/http-client/src/client.ts
packages/http-client/src/errors/request-error.ts
packages/http-client/src/errors/request-token-error.ts
packages/http-client/src/errors/response-error.ts
packages/http-client/src/errors/validation-error.ts
packages/http-client/tests/client.spec.ts
packages/http-client/tests/error.spec.ts
packages/http-server/.c8rc.json
packages/http-server/src/callback-error.ts
packages/protocol/.c8rc.json

- Boosted `http-client` to have 100% code coverage
- Removed seemingly unnecessary explicit calls of `setPrototypeOf()`
- Added `html` reporter for code coverage for local detailed report

Boosted http-client code coverage to 100% + minor updates

---

.changeset/fair-spiders-eat.md
packages/http-server/package.json
packages/http-server/src/request-handlers/get-exchanges.ts
packages/http-server/tests/create-exchange.spec.ts
packages/http-server/tests/get-exchange.spec.ts
packages/http-server/tests/get-exchanges.spec.ts
pnpm-lock.yaml

1. Fixed bug where IDs passed to getExchanges is handled incorrectly thus you cannot get exchanges given a list of IDs
2. Fixed bug in the test that is meant to test this (it always passes due to incorrect usage)
3. Fixed same issue in another test, switched to `sinon-chai` to give better readability and debug error message
4. 100% code coverage on `create-exchange.ts`

Fixed bug where IDs passed to getExchanges is handled incorrectly

---

.changeset/modern-bobcats-ring.md
packages/http-server/src/in-memory-exchanges-api.ts
packages/http-server/src/request-handlers/get-exchanges.ts
packages/http-server/src/types.ts
packages/http-server/tests/get-exchanges.spec.ts

Follow up for https://github.com/TBD54566975/tbdex/issues/312 to remove the query params.
Will also update the API implementation to return just the IDs as per #239 in a follow up PR.

Removed query params for List Exchanges API

---

CODEOWNERS
packages/protocol/tests/test-vectors.spec.ts

These tests perform a signature verification which involves resolution of DID DHT DIDs that can take more than 10s from time to time causing the tests to fail.
With this change all these tests now take less than 1 millisecond to run combined.
The intent of these tests seems to be validating the parsing logic, thus I think we don't actually need the real signature verification so we can just mock it.
Test coverage remains the same as other test have hit the signature verification methods.

#252 - Fixed long running parsing tests due to DID resolution

---

.changeset/odd-owls-invite.md
packages/http-client/src/client.ts
packages/http-server/src/request-handlers/create-exchange.ts
packages/http-server/src/request-handlers/submit-message.ts
packages/http-server/tests/create-exchange.spec.ts
packages/http-server/tests/submit-close.spec.ts
packages/http-server/tests/submit-message.spec.ts
packages/http-server/tests/submit-order.spec.ts
packages/protocol/README.md

Updated HTTP request body according to spec change in https://github.com/TBD54566975/tbdex/pull/344/files:
- Changed `rfq` property to `message` in create exchange request.
- Updated HTTP request body for `order` and `close` requests to have `message` container property.

Updated HTTP request body according to spec change

---

.changeset/selfish-apricots-act.md
.changeset/shiny-pillows-smile.md
packages/http-client/CHANGELOG.md
packages/http-client/package.json
packages/http-server/CHANGELOG.md
packages/http-server/package.json
packages/protocol/CHANGELOG.md
packages/protocol/package.json

Reverts TBD54566975/tbdex-js#262
Because v2.0.0 was not properly released and we want to group with the #264 release

Revert "Version Packages"
